### ISSUE TITLE
Doesn't work on Magento 2.2.3

### ISSUE THREAD

**Issue by mchumer** [opsway/magento2-module-amazonses#12]
I've installed from Magento Marketplace and, after, from github, via composer. I've filled the host address and the result was none.

Doesn't work.

Tks

**Comment by sandip5678** [comment]
try to make change in the di.xml is as follows:
Replace this
`<preference for="\Magento\Framework\Mail\Transport" type="OpsWay\EmailAmazonSES\Model\Transport"/>`

with this.
`<preference for="\Magento\Email\Model\Transport" type="OpsWay\EmailAmazonSES\Model\Transport"/>`

It may raise backward compatibility.
